image: php

before_script:
- apt-get update -yqq
- apt-get install -yqq git curl ca-certificates libxml2-dev
- docker-php-ext-install mbstring xml
- curl https://phar.phpunit.de/phpunit-7.5.1.phar -L -o phpunit.phar
- chmod +x phpunit.phar
- mv phpunit.phar /usr/local/bin/phpunit
- git clone git://github.com/splitbrain/dokuwiki.git
- pushd dokuwiki/lib/plugins
- ln -s $CI_PROJECT_DIR $CI_PROJECT_NAME
- popd

test:
  script:
  - cd dokuwiki/_test
  - phpunit --stderr --group plugin_ifauthex