stages:
  - test
  - release

unit_test:
  stage: test
  image: php
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git curl ca-certificates libxml2-dev
    - docker-php-ext-install mbstring xml
    - curl https://phar.phpunit.de/phpunit-7.5.1.phar -L -o phpunit.phar
    - chmod +x phpunit.phar
    - mv phpunit.phar /usr/local/bin/phpunit
    - git clone git://github.com/splitbrain/dokuwiki.git
    - pushd dokuwiki/lib/plugins
    - ln -s $CI_PROJECT_DIR $PLUGIN_NAME
    - popd
  script:
    - cd dokuwiki/_test
    - phpunit --stderr --group plugin_$PLUGIN_NAME
  variables:
    PLUGIN_NAME: ifauthex

package:
  image: alpine
  stage: release
  only:
    - tags
  before_script:
    - apk --update --no-cache add zip
  script:
    - zip -r $PLUGIN_NAME.zip *
  artifacts:
    paths:
      - "$PLUGIN_NAME.zip"
  variables:
    GIT_STRATEGY: clone
    PLUGIN_NAME: ifauthex
